---
- name: Create 'tower_sync_lab' role
  command: hammer role create --name tower_sync_lab

#- name: Create 'tower_sync_lab' role filters
#currently not possible to create filters through hammer

#- name: Create 'tower_sync_lab' user
  command:

- name: Create 'tower_sync_dev' role
  command: hammer role create --name tower_sync_dev

#- name: Create 'tower_sync_dev' user
#  command:

#need to document filters needed in readme to add manually
#need to document user creation and assigning of new role
